# Generated by Django 4.0 on 2022-08-08 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='prduct',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variantProduct',
            field=models.OneToOneField(blank=True, null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='shop.variantproduct'),
            preserve_default=b'I01\n',
        ),
    ]
