# Generated by Django 4.0 on 2022-08-09 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_review_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variantProduct',
            field=models.ForeignKey(blank=True, null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='shop.variantproduct'),
        ),
    ]
