# Generated by Django 4.0 on 2022-08-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_cartitem_variantproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(blank='true', default=0, null='true'),
        ),
    ]
