# Generated by Django 4.0 on 2022-08-11 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shop', '0009_order_note_orderitem_price_alter_cartitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='mobilephone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
