# Generated by Django 4.0 on 2022-08-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_address_order_mobilephone_order_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('d', 'delivered'), ('o', 'onway'), ('r', 'refunded')], default='o', max_length=10),
        ),
    ]
