# Generated by Django 4.0 on 2022-08-11 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_order_address_alter_order_mobilephone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='informations',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='telephone',
            new_name='mobilephone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mobilephone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='createDate',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variantProduct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.variantproduct'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
