# Generated by Django 4.0 on 2022-08-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_profile_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mobilephone',
            new_name='mobilePhone',
        ),
        migrations.AlterField(
            model_name='product',
            name='averageRating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
