# Generated by Django 4.0 on 2022-08-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_rename_mobilephone_profile_mobilephone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='averageRating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ratingCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
