# Generated by Django 4.0 on 2022-08-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[(1, 'دریافت شده'), (2, 'در حال آماده سازی'), (3, 'مرجوع شده')], default=2, max_length=10),
        ),
    ]
