# Generated by Django 4.0 on 2022-08-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.IntegerField(choices=[(1, 'دریافت شده'), (2, 'در حال آماده سازی'), (3, 'مرجوع شده')], default=2),
        ),
    ]
