# Generated by Django 4.0 on 2022-08-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(2, 'تحویل پست داده شد'), (1, 'در حال آماده سازی'), (3, 'دریافت شده')], default=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.IntegerField(choices=[(2, 'دریافت شده'), (1, 'در حال آماده سازی'), (3, 'مرجوع شده')], default=1),
        ),
    ]
